sys/loongarch/include/atomic.h: 同步函数
同步上游 commit：
	https://github.com/freebsd/freebsd-src/commit/2183004e14a863d65ca9192df1bea2625e3fdfb3#diff-065dd269f21c715b71a42ec3e16b4ecc1bfed2475d9a424211beb95855fa7468R150
	https://github.com/freebsd/freebsd-src/commit/a474e53d03ca8c78696fc222520de7d6876cc530#diff-065dd269f21c715b71a42ec3e16b4ecc1bfed2475d9a424211beb95855fa7468R549
	https://github.com/freebsd/freebsd-src/commit/a80b9ee15aa0f2da9f9f0c48e13324e0e5f2e840#diff-065dd269f21c715b71a42ec3e16b4ecc1bfed2475d9a424211beb95855fa7468R561

另外个编译出错补的
https://github.com/haowuge/freebsd-src/commit/bc40379ff8d9f199a58e3f6202c0c41fb246d538#diff-f5dc9c15ceca5efbc28ff8bdb1a9f11f034be4292bc99f6e54a6f1a44e2bcb16R594

/usr/local/bin/ccache cc -target loongarch64-unknown-freebsd14.2 --sysroot=/usr/obj/usr/src/loongarch.loongarch64/tmp -B/usr/obj/usr/src/loongarch.loongarch64/tmp/usr/bin  -O2 -pipe -fno-common -march=loongarch64 -mabi=lp64d  -fno-strict-aliasing -Werror -D_KERNEL -DKLD_MODULE -DKLD_TIED -nostdinc  -I/usr/src/sys/dev/cxgbe -DHAVE_KERNEL_OPTION_HEADERS -include /usr/obj/usr/src/loongarch.loongarch64/sys/GENERIC/opt_global.h -I. -I/usr/src/sys -I/usr/src/sys/contrib/ck/include -fno-common -g -fPIC -fdebug-prefix-map=./machine=/usr/src/sys/loongarch/include -I/usr/obj/usr/src/loongarch.loongarch64/sys/GENERIC     -MD  -MF.depend.t4_main.o -MTt4_main.o -ffreestanding -fwrapv -fstack-protector -Wall -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef -Wno-pointer-sign -D__printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error=tautological-compare -Wno-error=empty-body -Wno-error=parentheses-equality -Wno-error=unused-function -Wno-error=pointer-sign -Wno-error=shift-negative-value -Wno-address-of-packed-member -Wno-format-zero-length     -std=gnu99 -c /usr/src/sys/dev/cxgbe/t4_main.c -o t4_main.o
/usr/src/sys/dev/cxgbe/t4_main.c:1925:6: error: call to undeclared function 'atomic_testandset_int'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
 1925 |         if (atomic_testandset_int(&sc->error_flags, ilog2(ADAP_STOPPED))) {
      |             ^
/usr/src/sys/dev/cxgbe/t4_main.c:1925:6: note: did you mean 'atomic_testandset_long'?
/usr/src/sys/sys/_atomic_subword.h:238:1: note: 'atomic_testandset_long' declared here
  238 | atomic_testandset_long(volatile u_long *p, u_int v)
      | ^
/usr/src/sys/dev/cxgbe/t4_main.c:1957:7: error: call to undeclared function 'atomic_testandclear_int'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
 1957 |         if (!atomic_testandclear_int(&sc->error_flags, ilog2(ADAP_STOPPED))) {
      |              ^
/usr/src/sys/dev/cxgbe/t4_main.c:1957:7: note: did you mean 'atomic_testandclear_long'?
/usr/src/sys/sys/_atomic_subword.h:256:1: note: 'atomic_testandclear_long' declared here
  256 | atomic_testandclear_long(volatile u_long *p, u_int v)
      | ^
/usr/src/sys/dev/cxgbe/t4_main.c:3685:6: error: call to undeclared function 'atomic_testandclear_int'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
 3685 |         if (atomic_testandclear_int(&sc->error_flags, ilog2(ADAP_CIM_ERR))) {
      |             ^
/usr/src/sys/dev/cxgbe/t4_main.c:3713:6: error: call to undeclared function 'atomic_testandset_int'; ISO C99 and later do not support implicit function declarations [-Werror,-Wimplicit-function-declaration]
 3713 |         if (atomic_testandset_int(&sc->error_flags, ilog2(ADAP_FATAL_ERR)))
      |             ^
4 errors generated.
*** [t4_main.o] Error code 1

make[5]: stopped in /usr/src/sys/modules/cxgbe/if_cxgbe
1 error

make[5]: stopped in /usr/src/sys/modules/cxgbe/if_cxgbe